# Generated by Django 4.2.13 on 2024-06-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='last_name',
        ),
    ]
