# Generated by Django 4.2.13 on 2024-06-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_influenceraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influenceraccount',
            name='instagram_id',
        ),
        migrations.CreateModel(
            name='InfluencerInstagramInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=255, null=True)),
                ('biography', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('following', models.IntegerField(blank=True, null=True)),
                ('posts', models.IntegerField(blank=True, null=True)),
                ('long_access_token', models.CharField(blank=True, max_length=300, null=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount')),
            ],
        ),
    ]
