# Generated by Django 4.2.13 on 2024-06-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_influenceraccount_instagram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerinstagraminformation',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
