# Generated by Django 4.2.13 on 2024-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_influencerinstagraminformation_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerinstagraminformation',
            name='profile_picture_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='influencerinstagraminformation',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
