# Generated by Django 4.2.13 on 2024-06-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_influencerinstagraminformation_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerinstagraminformation',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
    ]
