# Generated by Django 4.2.13 on 2024-06-23 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_influencerinstagraminformation_influencer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_description', models.CharField(blank=True, max_length=100, null=True)),
                ('post_length', models.IntegerField(blank=True, null=True)),
                ('post_length_applicable', models.BooleanField(default=False)),
                ('instagram_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influencerinstagraminformation')),
            ],
        ),
        migrations.CreateModel(
            name='FeedPostService',
            fields=[
                ('baseservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseservice')),
                ('post_price_per_hour', models.FloatField(blank=True, null=True)),
            ],
            bases=('core.baseservice',),
        ),
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('baseservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseservice')),
                ('custom_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            bases=('core.baseservice',),
        ),
        migrations.CreateModel(
            name='ReelPostService',
            fields=[
                ('baseservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseservice')),
                ('post_price_per_hour', models.FloatField(blank=True, null=True)),
            ],
            bases=('core.baseservice',),
        ),
        migrations.CreateModel(
            name='StoryPostService',
            fields=[
                ('baseservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseservice')),
                ('post_price_per_hour', models.FloatField(blank=True, null=True)),
            ],
            bases=('core.baseservice',),
        ),
        migrations.CreateModel(
            name='UGCService',
            fields=[
                ('baseservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseservice')),
                ('post_price', models.FloatField(blank=True, null=True)),
            ],
            bases=('core.baseservice',),
        ),
    ]
