# Generated by Django 4.2.13 on 2024-06-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_baseservice_feedpostservice_otherservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseservice',
            name='post_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
