# Generated by Django 4.2.13 on 2024-07-02 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_instagrambase_instagramagedemographics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramInitialInformation',
            fields=[
                ('instagrambase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.instagrambase')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('biography', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('following', models.IntegerField(blank=True, null=True)),
                ('posts', models.IntegerField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=('core.instagrambase',),
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='following',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='profile_picture_url',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='username',
        ),
        migrations.RemoveField(
            model_name='influencerinstagraminformation',
            name='website',
        ),
    ]
