# Generated by Django 4.2.13 on 2024-07-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_instagraminitialinformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagraminitialinformation',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='instagraminitialinformation',
            old_name='following',
            new_name='follows_count',
        ),
        migrations.RenameField(
            model_name='instagraminitialinformation',
            old_name='posts',
            new_name='media_count',
        ),
    ]
