# Generated by Django 4.2.13 on 2024-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_followers_instagraminitialinformation_followers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramdetails',
            name='profile_views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
