# Generated by Django 4.2.13 on 2024-07-02 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_instagramdetails_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrambase',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
