# Generated by Django 4.2.13 on 2024-07-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_instagrambase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramdetails',
            old_name='saved',
            new_name='saves',
        ),
    ]
