# Generated by Django 4.2.13 on 2024-07-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_saved_instagramdetails_saves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrammediadata',
            old_name='comment_count',
            new_name='comments_count',
        ),
        migrations.RenameField(
            model_name='instagrammediadata',
            old_name='saved_count',
            new_name='saved',
        ),
        migrations.RenameField(
            model_name='instagrammediadata',
            old_name='shares_count',
            new_name='shares',
        ),
    ]
