# Generated by Django 4.2.13 on 2024-07-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_comment_count_instagrammediadata_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediadata',
            name='is_comment_enabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='instagrammediadata',
            name='is_share_to_feed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
