# Generated by Django 4.2.13 on 2024-07-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_instagrammediadata_is_comment_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediadata',
            name='is_comment_enabled',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instagrammediadata',
            name='is_share_to_feed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
