# Generated by Django 4.2.13 on 2024-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_instagrammediadata_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagrammediacomment',
            old_name='comment_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='instagrammediacomment',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
