# Generated by Django 4.2.13 on 2024-07-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_comment_user_instagrammediacomment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediacomment',
            name='hidden',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
