# Generated by Django 4.2.13 on 2024-07-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_instagrammediadata_media_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrammediadata',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
