# Generated by Django 4.2.13 on 2024-07-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contract_contractversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
