# Generated by Django 4.2.13 on 2024-07-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_contract_contract_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractversion',
            name='contract_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractversion',
            name='contract_visible',
            field=models.BooleanField(default=False),
        ),
    ]
