# Generated by Django 4.2.13 on 2024-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_contractversion_contract_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractversion',
            name='sign_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
