# Generated by Django 4.2.13 on 2024-07-09 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_contractversion_sign_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractversion',
            name='sign_state',
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contractversion')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
