# Generated by Django 4.2.13 on 2024-07-09 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_remove_contractversion_sign_state_signaturerequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignatureRequest',
            new_name='SignatureRequests',
        ),
    ]
