# Generated by Django 4.2.13 on 2024-07-09 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_rename_signaturerequest_signaturerequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractuserpermissions',
            name='document_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='signaturerequests',
            unique_together={('contract', 'contract_version', 'request_user', 'request_date')},
        ),
    ]
