# Generated by Django 4.2.13 on 2024-07-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_contractuserpermissions_document_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractuserpermissions',
            name='document_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='document_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
