# Generated by Django 4.2.13 on 2024-07-13 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_files_signaturerequests_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file_owner',
        ),
        migrations.AddField(
            model_name='files',
            name='users',
            field=models.ManyToManyField(related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
