# Generated by Django 4.2.13 on 2024-07-14 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_remove_files_file_owner_files_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractversion',
            name='file_uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploader', to=settings.AUTH_USER_MODEL),
        ),
    ]
