# Generated by Django 4.2.13 on 2024-07-14 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_contractversion_file_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractversion',
            name='file_upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
