# Generated by Django 4.2.13 on 2024-07-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_contractversion_file_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='influencerInstagramInformation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influencerinstagraminformation'),
        ),
    ]
