# Generated by Django 4.2.13 on 2024-07-16 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_alter_contractversion_file_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('post_type', models.CharField(blank=True, max_length=100, null=True)),
                ('post_length', models.IntegerField(blank=True, null=True)),
                ('content_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_content_provider', to=settings.AUTH_USER_MODEL)),
                ('instagram_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influencerinstagraminformation')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
    ]
