# Generated by Django 4.2.13 on 2024-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_service_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='instagram_information',
            new_name='influencer_instagram_information',
        ),
        migrations.AlterField(
            model_name='service',
            name='content_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
