# Generated by Django 4.2.13 on 2024-07-23 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
