# Generated by Django 4.2.13 on 2024-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_requests_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammediadata',
            name='transcribed',
            field=models.BooleanField(default=False),
        ),
    ]
