# Generated by Django 4.2.13 on 2024-08-04 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_instagrammediadata_transcribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_url', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('subscriber_count', models.IntegerField(blank=True, null=True)),
                ('video_count', models.IntegerField(blank=True, null=True)),
                ('hidden_subscriber_count', models.BooleanField(default=False)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideoInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('channel_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubechannelinformation')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('estimated_minutes_watched', models.IntegerField(blank=True, null=True)),
                ('average_view_duration', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('reach', models.IntegerField(blank=True, null=True)),
                ('video_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubevideoinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YouTubeGeographicDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('channel_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubechannelinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YouTubeGenderDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('male_percentage', models.FloatField(blank=True, null=True)),
                ('female_percentage', models.FloatField(blank=True, null=True)),
                ('unknown_percentage', models.FloatField(blank=True, null=True)),
                ('channel_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubechannelinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YouTubeChannelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('estimated_minutes_watched', models.IntegerField(blank=True, null=True)),
                ('average_view_duration', models.IntegerField(blank=True, null=True)),
                ('total_interactions', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('dislikes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
                ('channel_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubechannelinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YouTubeAgeDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('age_group_13_17', models.FloatField(blank=True, null=True)),
                ('age_group_18_24', models.FloatField(blank=True, null=True)),
                ('age_group_25_34', models.FloatField(blank=True, null=True)),
                ('age_group_35_44', models.FloatField(blank=True, null=True)),
                ('age_group_45_54', models.FloatField(blank=True, null=True)),
                ('age_group_55_64', models.FloatField(blank=True, null=True)),
                ('age_group_65_plus', models.FloatField(blank=True, null=True)),
                ('channel_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubechannelinformation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
