# Generated by Django 4.2.13 on 2024-08-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_youtubechannelinformation_youtubevideoinformation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannelinformation',
            name='influencer',
        ),
    ]
