# Generated by Django 4.2.13 on 2024-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_youtubechannelinformation_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannelinformation',
            name='access_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannelinformation',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannelinformation',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
