# Generated by Django 4.2.13 on 2024-08-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_youtubechannelinformation_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeagedemographics',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
        migrations.AddField(
            model_name='youtubechannelanalytics',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
        migrations.AddField(
            model_name='youtubegenderdemographics',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
        migrations.AddField(
            model_name='youtubegeographicdemographics',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
        migrations.AddField(
            model_name='youtubevideoanalytics',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
    ]
