# Generated by Django 4.2.13 on 2024-08-04 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_youtubeagedemographics_influencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannelinformation',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='youtubechannelinformation',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount'),
        ),
    ]
