# Generated by Django 4.2.13 on 2024-08-06 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_youtubechannelinformation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('post_type', models.CharField(blank=True, max_length=100, null=True)),
                ('post_length', models.IntegerField(blank=True, null=True)),
                ('content_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubechannelinformation')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_pricings', to='core.youtubeservice')),
            ],
        ),
    ]
