# Generated by Django 4.2.13 on 2024-08-10 03:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_youtubeservice_youtubeservicepricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessaccount')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.youtubeservice')),
            ],
        ),
    ]
