# Generated by Django 4.2.13 on 2025-01-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_youtuberequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_access_token', models.CharField(blank=True, max_length=300, null=True)),
                ('tiktok_access_scope', models.CharField(blank=True, max_length=300, null=True)),
                ('tiktok_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount')),
            ],
        ),
        migrations.CreateModel(
            name='TikTokAccountInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok_sec_uid', models.CharField(blank=True, max_length=200, null=True)),
                ('tiktok_nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('tiktok_avatar', models.CharField(blank=True, max_length=1000, null=True)),
                ('tiktok_digg_count', models.IntegerField()),
                ('tiktok_follower_count', models.IntegerField()),
                ('tiktok_following_count', models.IntegerField()),
                ('tiktok_friend_count', models.IntegerField()),
                ('tiktok_heart', models.IntegerField()),
                ('tiktok_video_count', models.IntegerField()),
                ('tiktok_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tiktokaccount')),
            ],
        ),
    ]
