# Generated by Django 4.2.13 on 2025-01-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_tiktokaccount_tiktokaccountinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccountinformation',
            name='tiktok_signature',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
