# Generated by Django 4.2.13 on 2025-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_tiktokaccountinformation_tiktok_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiktokaccountinformation',
            name='tiktok_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
