# Generated by Django 4.2.13 on 2025-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_tiktokaccountinformation_tiktok_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokaccountinformation',
            name='id',
        ),
        migrations.AlterField(
            model_name='tiktokaccountinformation',
            name='tiktok_unique_id',
            field=models.CharField(default=-1, max_length=100, primary_key=True, serialize=False),
        ),
    ]
