# Generated by Django 4.2.13 on 2025-01-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_tiktokaccountinformation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiktokaccountinformation',
            name='tiktok_account',
        ),
        migrations.DeleteModel(
            name='TikTokAccount',
        ),
        migrations.DeleteModel(
            name='TikTokAccountInformation',
        ),
    ]
