# Generated by Django 4.2.13 on 2025-01-25 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_tiktokaccountinformation_tiktok_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylloAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_status', models.CharField(blank=True, max_length=50, null=True)),
                ('phyllo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.influenceraccount')),
            ],
        ),
        migrations.CreateModel(
            name='PhylloSDKToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_sdk_token', models.CharField(blank=True, max_length=300, null=True)),
                ('phyllo_expires_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloaccount')),
            ],
        ),
    ]
