# Generated by Django 4.2.13 on 2025-01-26 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_phylloaccount_phyllosdktoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylloAddedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_accountid', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_work_platform_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloaccount')),
            ],
        ),
    ]
