# Generated by Django 4.2.13 on 2025-01-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_phyllocontentdata_phyllocomments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylloAudienceDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_gender_demographics_male', models.IntegerField(blank=True, null=True)),
                ('phyllo_gender_demographics_female', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_13_17', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_18_24', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_25_32', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_33_39', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_40_49', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_50_69', models.IntegerField(blank=True, null=True)),
                ('phyllo_age_60_plus', models.IntegerField(blank=True, null=True)),
                ('phyllo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloaddedaccounts')),
            ],
        ),
    ]
