# Generated by Django 4.2.13 on 2025-01-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_phylloaudiencedemographics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phylloaudiencedemographics',
            old_name='phyllo_age_50_69',
            new_name='phyllo_age_50_59',
        ),
        migrations.AddField(
            model_name='phylloaudiencedemographics',
            name='phyllo_gender_demographics_other',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
