# Generated by Django 4.2.13 on 2025-01-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_rename_phyllo_age_50_69_phylloaudiencedemographics_phyllo_age_50_59_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_13_17',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_18_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_25_32',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_33_39',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_40_49',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_50_59',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_age_60_plus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_gender_demographics_female',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_gender_demographics_male',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='phyllo_gender_demographics_other',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhylloAudienceCountryDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_demographics', to='core.phylloaudiencedemographics')),
            ],
        ),
        migrations.CreateModel(
            name='PhylloAudienceCityDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_demographics', to='core.phylloaudiencedemographics')),
            ],
        ),
    ]
