# Generated by Django 4.2.13 on 2025-01-28 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_phylloaudiencedemographics_phyllo_age_13_17_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 28, 11, 41, 8, 848342), null=True),
        ),
    ]
