# Generated by Django 4.2.13 on 2025-01-29 01:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_phylloaudiencedemographics_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 29, 4, 50, 47, 447085), null=True),
        ),
        migrations.CreateModel(
            name='PhylloScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('visibility', models.CharField(blank=True, max_length=20, null=True)),
                ('retry', models.BooleanField(default=False)),
                ('media_media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('media_source_media_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('media_thumbnail_offset', models.IntegerField(blank=True, null=True)),
                ('media_additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.CharField(blank=True, default='scheduled', max_length=100, null=True)),
                ('phyllo_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloaddedaccounts')),
            ],
        ),
    ]
