# Generated by Django 4.2.13 on 2025-02-04 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_campaign_alter_phylloaudiencedemographics_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='status',
            field=models.CharField(blank=True, default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 4, 21, 58, 59, 562643), null=True),
        ),
    ]
