# Generated by Django 4.2.13 on 2025-02-04 23:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_campaign_timestamp_campaigninfluencer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=10, null=True)),
                ('pricing_method', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('content_provider', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 2, 52, 23, 915618), null=True),
        ),
        migrations.AddConstraint(
            model_name='campaigninfluencer',
            constraint=models.UniqueConstraint(fields=('campaign', 'influencer'), name='unique_campaign_influencer'),
        ),
        migrations.AddField(
            model_name='influencerservice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloaddedaccounts'),
        ),
        migrations.AddConstraint(
            model_name='influencerservice',
            constraint=models.UniqueConstraint(fields=('account', 'service_type', 'pricing_method', 'content_provider'), name='unique_influencer_service'),
        ),
    ]
