# Generated by Django 4.2.13 on 2025-02-04 23:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_influencerservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.influencerservice'),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 2, 54, 34, 434629), null=True),
        ),
    ]
