# Generated by Django 4.2.13 on 2025-02-05 00:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0071_campaign_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 3, 17, 54, 967610), null=True),
        ),
    ]
