# Generated by Django 4.2.13 on 2025-02-05 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_campaign_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 21, 24, 46, 585013), null=True),
        ),
    ]
