# Generated by Django 4.2.13 on 2025-02-05 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_campaigninfluencer_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 5, 21, 26, 12, 793648), null=True),
        ),
    ]
