# Generated by Django 4.2.13 on 2025-02-05 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_campaigninfluencer_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='influencerservice',
            name='unique_influencer_service',
        ),
        migrations.RemoveField(
            model_name='influencerservice',
            name='content_provider',
        ),
        migrations.AddField(
            model_name='influencerservice',
            name='content_provider_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerservice',
            name='content_provider_influencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influencerservice',
            name='pricing_method_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 6, 2, 12, 25, 304017), null=True),
        ),
        migrations.AddConstraint(
            model_name='influencerservice',
            constraint=models.UniqueConstraint(fields=('account', 'service_type', 'pricing_method'), name='unique_influencer_service'),
        ),
    ]
