# Generated by Django 4.2.13 on 2025-02-06 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_influencerservice_unique_influencer_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='content_provider',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 6, 11, 34, 15, 658095), null=True),
        ),
    ]
