# Generated by Django 4.2.13 on 2025-02-08 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_campaigninfluencer_content_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='influencer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='influencerInstagramInformation',
        ),
        migrations.AddField(
            model_name='contract',
            name='phyllo_added_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phylloaddedaccounts'),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 8, 10, 6, 9, 376273), null=True),
        ),
    ]
