# Generated by Django 4.2.13 on 2025-02-10 03:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_contract_influencer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 10, 6, 18, 21, 847686), null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='media_media_type',
            field=models.CharField(blank=True, default='VIDEO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='type',
            field=models.CharField(blank=True, default='VIDEO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='visibility',
            field=models.CharField(blank=True, default='PUBLIC', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('business', 'phyllo_added_account')},
        ),
        migrations.CreateModel(
            name='CampaignFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=400, null=True)),
                ('file_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('file_size', models.PositiveBigIntegerField()),
                ('file_url', models.CharField(blank=True, max_length=3000, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
            ],
        ),
    ]
