# Generated by Django 4.2.13 on 2025-02-10 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_phylloaudiencedemographics_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 10, 11, 55, 45, 981890), null=True),
        ),
    ]
