# Generated by Django 4.2.13 on 2025-02-11 22:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_phylloaudiencedemographics_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='business_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='business_contract_signed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='campaign_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaignfiles'),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='influencer_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='influencer_contract_signed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='payment_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 1, 28, 39, 163400), null=True),
        ),
    ]
