# Generated by Django 4.2.13 on 2025-02-12 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_phylloscheduledpost_business_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaign'),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='document_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 11, 59, 57, 137744), null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='business_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='business_contract_signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='influencer_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='influencer_contract_signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='phylloscheduledpost',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
