# Generated by Django 4.2.13 on 2025-02-12 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_phylloscheduledpost_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phylloscheduledpost',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='phylloscheduledpost',
            name='campaign_files',
        ),
        migrations.AddField(
            model_name='contract',
            name='campaign_influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaigninfluencer'),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='campaign_influencers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaigninfluencer'),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 13, 39, 44, 898868), null=True),
        ),
    ]
