# Generated by Django 4.2.13 on 2025-02-12 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_remove_phylloscheduledpost_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaigninfluencer',
            name='unique_campaign_influencer',
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 13, 49, 6, 592063), null=True),
        ),
        migrations.AddConstraint(
            model_name='campaigninfluencer',
            constraint=models.UniqueConstraint(fields=('campaign', 'influencer', 'timestamp'), name='unique_campaign_influencer'),
        ),
    ]
