# Generated by Django 4.2.13 on 2025-02-12 13:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_remove_campaigninfluencer_unique_campaign_influencer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='campaign_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.campaignfiles'),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 16, 48, 5, 135511), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('business', 'phyllo_added_account', 'contract_id')},
        ),
    ]
