# Generated by Django 4.2.13 on 2025-02-18 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_phylloscheduledpost_campaign_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='content_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='final_status',
            field=models.CharField(blank=True, default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 9, 37, 12, 504121), null=True),
        ),
        migrations.CreateModel(
            name='PhylloPostedContentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_contentid', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_accountid', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_account_platform_username', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_work_platform_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_work_platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_work_platform_logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_engagement_like_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_dislike_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_comment_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_impression_organic_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_reach_organic_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_save_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_view_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_watch_time_in_hours', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_share_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_impression_paid_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_engagement_reach_paid_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_format', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_type', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_media_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('phyllo_visibility', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_thumbnail_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_published_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_platform_profile_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_platform_profile_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_sponsored', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_collaboration', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloscheduledpost')),
            ],
        ),
        migrations.CreateModel(
            name='PhylloPostedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_comment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_published_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_accountid', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_platform_username', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_work_platform_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pyllo_work_platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_logo_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('phyllo_contentid', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_content_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('phyllo_content_published_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('phyllo_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_text', models.CharField(blank=True, max_length=10000, null=True)),
                ('phyllo_commenter_username', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_commenter_display_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_commenter_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phyllo_commenter_profile_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('phyllo_like_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_reply_count', models.IntegerField(blank=True, null=True)),
                ('phyllo_scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloscheduledpost')),
            ],
        ),
        migrations.CreateModel(
            name='PhylloPostedAudienceDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phyllo_gender_demographics_male', models.FloatField(blank=True, null=True)),
                ('phyllo_gender_demographics_female', models.FloatField(blank=True, null=True)),
                ('phyllo_gender_demographics_other', models.FloatField(blank=True, null=True)),
                ('phyllo_age_13_17', models.FloatField(blank=True, null=True)),
                ('phyllo_age_18_24', models.FloatField(blank=True, null=True)),
                ('phyllo_age_25_32', models.FloatField(blank=True, null=True)),
                ('phyllo_age_33_39', models.FloatField(blank=True, null=True)),
                ('phyllo_age_40_49', models.FloatField(blank=True, null=True)),
                ('phyllo_age_50_59', models.FloatField(blank=True, null=True)),
                ('phyllo_age_60_plus', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 9, 37, 12, 508121), null=True)),
                ('phyllo_scheduled_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.phylloscheduledpost')),
            ],
        ),
        migrations.CreateModel(
            name='PhylloPostedAudienceCountryDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_posted_demographics', to='core.phylloaudiencedemographics')),
            ],
        ),
        migrations.CreateModel(
            name='PhylloPostedAudienceCityDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('demographics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_posted_demographics', to='core.phylloaudiencedemographics')),
            ],
        ),
    ]
