# Generated by Django 4.2.13 on 2025-02-19 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_phylloscheduledpost_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phylloscheduledpost',
            name='publish_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 16, 3, 21, 413588), null=True),
        ),
        migrations.AlterField(
            model_name='phyllopostedaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 16, 3, 21, 418589), null=True),
        ),
    ]
