# Generated by Django 4.2.13 on 2025-03-04 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_phylloscheduledpost_publish_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerservice',
            name='content_provider_business',
        ),
        migrations.RemoveField(
            model_name='influencerservice',
            name='content_provider_influencer',
        ),
        migrations.AddField(
            model_name='influencerservice',
            name='content_provider',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='influencerservice',
            name='pricing_method_activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 4, 23, 9, 35, 775830), null=True),
        ),
        migrations.AlterField(
            model_name='phyllopostedaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 4, 23, 9, 35, 780823), null=True),
        ),
    ]
