# Generated by Django 4.2.13 on 2025-03-04 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_remove_influencerservice_content_provider_business_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='influencerservice',
            name='unique_influencer_service',
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 4, 23, 15, 6, 387905), null=True),
        ),
        migrations.AlterField(
            model_name='phyllopostedaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 4, 23, 15, 6, 391906), null=True),
        ),
        migrations.AddConstraint(
            model_name='influencerservice',
            constraint=models.UniqueConstraint(fields=('account', 'service_type', 'pricing_method', 'content_provider'), name='unique_influencer_service'),
        ),
    ]
