# Generated by Django 4.2.13 on 2025-03-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_influencerservice_unique_influencer_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='num_posts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phylloaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 5, 4, 51, 39, 466393), null=True),
        ),
        migrations.AlterField(
            model_name='phyllopostedaudiencedemographics',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 5, 4, 51, 39, 470393), null=True),
        ),
    ]
