# Generated by Django 4.2.13 on 2024-07-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chat_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
