# Generated by Django 4.2.13 on 2024-07-22 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmodel_chat_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 15, 40, 1, 502160)),
        ),
    ]
