# Generated by Django 4.2.13 on 2025-01-25 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 11, 43, 5, 337184)),
        ),
    ]
