# Generated by Django 4.2.13 on 2025-02-05 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0044_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 2, 10, 20, 855368)),
        ),
    ]
