# Generated by Django 4.2.13 on 2025-02-05 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0046_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 6, 2, 12, 25, 86417)),
        ),
    ]
