# Generated by Django 4.2.13 on 2025-02-10 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0049_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 6, 18, 21, 627691)),
        ),
    ]
