# Generated by Django 4.2.13 on 2025-02-19 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0057_alter_message_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 16, 3, 21, 237352)),
        ),
    ]
